# Generated by Django 3.2.5 on 2022-05-03 20:25

import account.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32, null=True)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32, null=True)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('full_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Country', 'Country'), ('State/Province', 'State/Province')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_entity', to='account.financialentity')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_entity', to='account.financialentity')),
            ],
        ),
        migrations.CreateModel(
            name='StockMarketTrade',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('ticker', models.CharField(max_length=10)),
                ('bought_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shares', models.IntegerField()),
                ('bought_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold_on', models.DateTimeField(null=True)),
                ('sold_value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            bases=('account.transaction',),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('region', models.ManyToManyField(related_name='region', to='account.Region')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18, null=True, validators=[account.validators.validate_phone_number])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transfer')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('due_date', models.DateField(null=True)),
            ],
            bases=('account.transfer',),
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transfer')),
            ],
            bases=('account.transfer',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transfer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.transfer')),
                ('reason', models.CharField(max_length=50)),
            ],
            bases=('account.transfer',),
        ),
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('financialentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.financialentity')),
                ('full_name', models.CharField(max_length=40)),
                ('timezone', models.CharField(default='UTC', max_length=12)),
                ('open_hour', models.DecimalField(decimal_places=2, default=9.5, max_digits=4)),
                ('close_hour', models.DecimalField(decimal_places=2, default=4.0, max_digits=4)),
                ('lunch_start_hour', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('lunch_end_hour', models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.region')),
            ],
            bases=('account.financialentity',),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('financialentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.financialentity')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attribute', to='account.accountattribute')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type', to='account.accounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.financialentity',),
        ),
        migrations.CreateModel(
            name='StockMarketAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.account')),
                ('stock_market', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_market', to='account.stockmarket')),
            ],
            bases=('account.account',),
        ),
    ]
